### ISSUE TITLE
Error: private key length is invalid

### ISSUE THREAD

**Issue by gasparyanyur** [ethereumjs/ethereumjs-util#158]
Hi all. I am trying to generate public key from private. So I have took the private key from metamask and when trying to generate public key I am getting an error look like this

My scipt:

```
const util  = require('ethereumjs-util')

const privateKey = 'my_priv_key';


var public = util.privateToPublic(privateKey);

console.log(public);
```

Here is an error response:

```
C:\Users\EvenPC\Even\hd-wallets\node_modules\secp256k1\lib\assert.js:31
  if (buffer.length !== length) throw RangeError(message)
                                ^

RangeError: private key length is invalid
    at Object.exports.isBufferLength (C:\Users\EvenPC\Even\hd-wallets\node_modules\secp256k1\lib\assert.js:31:39)
    at Object.publicKeyCreate (C:\Users\EvenPC\Even\hd-wallets\node_modules\secp256k1\lib\index.js:75:14)
    at Object.exports.privateToPublic (C:\Users\EvenPC\Even\hd-wallets\node_modules\ethereumjs-util\dist\index.js:332:20)
    at Object.<anonymous> (C:\Users\EvenPC\Even\hd-wallets\main.js:6:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)

```

**Comment by fanatid** [comment]
I'm not sure how anybody will able to help in this situation.

**Comment by holgerd77** [comment]
Same here, please ask on Gitter.
